name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.x' # Or your preferred Go version

    - name: Build Go Application
      run: go build -v ./...

    - name: Run Go Tests and Generate Coverage
      run: |
        go test -v -coverprofile=coverage.out ./...
        go tool cover -html=coverage.out -o coverage.html

    - name: Display Go Coverage Summary
      run: |
        # Generate a functional coverage report and extract the total percentage
        COVERAGE_PERCENTAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}')
        
        # Output the coverage percentage to the GitHub Actions summary
        echo "### Go Code Coverage" >> $GITHUB_STEP_SUMMARY
        echo "Total Coverage: **${COVERAGE_PERCENTAGE}**" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "For a detailed report, download the 'go-coverage-report' artifact and open 'coverage.html'." >> $GITHUB_STEP_SUMMARY

    - name: Upload Coverage Report Artifact
      uses: actions/upload-artifact@v4
      with:
        name: go-coverage-report
        path: |
          coverage.out
          coverage.html

  e2e-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.x' # Ensure Go is available for 'go run' in the script

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Ensure Node.js is available for npm/npx in the script

    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: |
          /home/runner/.cache/ms-playwright
        key: playwright-browsers-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          playwright-browsers-${{ runner.os }}-

    - name: Run E2E Tests Script
      run: chmod +x run-e2e-tests.sh && ./run-e2e-tests.sh
